import { Easing } from 'react-native-reanimated';

const DEFAULT_ITEM_ANIMATION_EASING = Easing.out(Easing.exp);
const DEFAULT_ITEM_ANIMATION_DURATION = 500;
const DEFAULT_ITEM_INNER_SPACE = 12;
const DEFAULT_ITEM_OUTER_SPACE = 12;
const DEFAULT_ITEM_ICON_SIZE = 24;

export {
  DEFAULT_ITEM_ANIMATION_EASING,
  DEFAULT_ITEM_ANIMATION_DURATION,
  DEFAULT_ITEM_INNER_SPACE,
  DEFAULT_ITEM_OUTER_SPACE,
  DEFAULT_ITEM_ICON_SIZE,
};
