import Animated, { Easing } from 'react-native-reanimated';

const DEFAULT_ITEM_ANIMATION_EASING: Animated.EasingFunction = Easing.out(
  Easing.exp
);
const DEFAULT_ITEM_ANIMATION_DURATION = 750;
const DEFAULT_ITEM_INNER_SPACE = 24;
const DEFAULT_ITEM_ICON_SIZE = 20;
const DEFAULT_INDICATOR_VISIBLITY = true;
const DEFAULT_INDICATOR_SIZE = 6;
const DEFAULT_INDICATOR_COLOR = 'black';
const DEFAULT_ITEM_LAYOUT_DIRECTION = false;

export {
  DEFAULT_ITEM_ANIMATION_EASING,
  DEFAULT_ITEM_ANIMATION_DURATION,
  DEFAULT_ITEM_INNER_SPACE,
  DEFAULT_ITEM_ICON_SIZE,
  DEFAULT_INDICATOR_VISIBLITY,
  DEFAULT_INDICATOR_SIZE,
  DEFAULT_INDICATOR_COLOR,
  DEFAULT_ITEM_LAYOUT_DIRECTION,
};
